-- AlterTable
ALTER TABLE `Problem` ADD COLUMN `againCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `easyCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `goodCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `hardCount` INTEGER NOT NULL DEFAULT 0;
