-- AlterTable
ALTER TABLE `Collection` ADD COLUMN `learningCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `newCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `reviewCount` INTEGER NOT NULL DEFAULT 0;
