-- AlterTable
ALTER TABLE `Problem` ADD COLUMN `creationDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `dueDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `ease` DOUBLE NOT NULL DEFAULT 2.5,
    ADD COLUMN `interval` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `type` VARCHAR(191) NOT NULL DEFAULT 'New';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `easyBonus` DOUBLE NOT NULL DEFAULT 1.3,
    ADD COLUMN `easyInterval` INTEGER NOT NULL DEFAULT 4,
    ADD COLUMN `graduatingInterval` INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN `intervalModifier` DOUBLE NOT NULL DEFAULT 1.0,
    ADD COLUMN `learnSteps` VARCHAR(191) NOT NULL DEFAULT '10m 1d',
    ADD COLUMN `maximumInterval` INTEGER NOT NULL DEFAULT 180,
    ADD COLUMN `maximumNewPerDay` INTEGER NOT NULL DEFAULT 9999,
    ADD COLUMN `minimumEase` DOUBLE NOT NULL DEFAULT 1.3,
    ADD COLUMN `relearnGraduatingInterval` DOUBLE NOT NULL DEFAULT 0.75,
    ADD COLUMN `relearnSteps` VARCHAR(191) NOT NULL DEFAULT '10m',
    ADD COLUMN `startingEase` DOUBLE NOT NULL DEFAULT 2.5;
